version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.11
    commands:
      - echo "Installing dependencies..."
      - pip install apache-airflow-providers-amazon
      - pip install -r requirement.txt -t lib
      - pip install apache-airflow-providers-amazon
  build:
    commands:
      - echo "Zipping deployment package..."
      - cd lib
      - zip -r9 ../emrjob_deployment_package.zip .
      - cd ..
      - zip -g emrjob_deployment_package.zip airflow-s3-emr-redshift.py
  post_build:
    commands:
      - echo "Uploading to S3..."
      - aws s3 cp emrjob_deployment_package.zip s3://s3-airflow-scripts/dev-dags/
      - echo "Deployment complete!"